<template>
  <v-container
    class="
      grey
      lighten-5
      black--text
      px-4 py-8
    "
    id="skills-container"
    fluid
  >
    <v-row
      align="center"
      justify="center">
      <v-col
        class="text-center"
      >
        <h1
          :class="`
            text-h4
            text-md-h3
            ${themeColorText}
          `"
          id="nav-skills"
        >Skills At a Glance</h1>
      </v-col>
    </v-row>
    <v-lazy
      :value="skillsC"
      @value="setSkillsC"
      :options="{
        rootMargin: '80%',
        threshold: 1,
      }"
      min-height="100vh"
      transition='scroll-y-reverse-transition'
      v-intersect="onSkillsIntersect"
    >
      <v-row
        justify="center"
        class="mx-4"
      >
        <v-col
          cols="10"
          md="4"
          class="elevation-16 pa-4"
        >
          <h4
            :class="`
            text-heading-5
            text-md-heading-4
            font-weight-bold
            ${themeColorText}
            ml-4
            text-decoration-underline
          `">Software</h4>
          <div class="text-body-2
            text-md-body-1
            mx-4"
          >
            <v-chip
              class="
                ma-2
                elevation-8
              "
              :color="skillsChipTitleColor"
            >
              <v-icon left>
              mdi-fire
              </v-icon>
              <span
              class="text-decoration-underline">
              Proficient:
              </span>
            </v-chip>
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >Vue.js</v-chip>
            {
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >Vue Router
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >VueX Store
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >Vuetify.js
            </v-chip>
            }
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >Express.js</v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >Adonis.js</v-chip>
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >C</v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >C++</v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >Java</v-chip>
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >html5</v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >css3</v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >javascript</v-chip>
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >jQuery</v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >AJAX</v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >JSON</v-chip>
            <br />
            <v-chip
              class="
                ma-2
                elevation-8
              "
              :color="skillsChipTitleColor"
            >
              <v-icon left>
              mdi-pine-tree-fire
              </v-icon>
              <span
              class="text-decoration-underline">
              Familiar:
              </span>
            </v-chip>
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >Selenium
            </v-chip>
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >php
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >PDO
            </v-chip>
            <br />
            <v-chip
              class="
                ma-2
                elevation-8
                text-decoration-underline
              "
              :color="skillsChipTitleColor"
            >
              Version control:
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >git
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >SVN
            </v-chip>
            <br />
            <v-chip
              class="
                ma-2
                elevation-8
                text-decoration-underline
              "
              :color="skillsChipTitleColor"
            >
              Database:
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >SQL
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >MongoDB
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >MySQL
            </v-chip>
            <br />
            <v-chip
              class="
                ma-2
                elevation-8
                text-decoration-underline
              "
              :color="skillsChipTitleColor"
            >
              Cloud/Serverless:
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >Firebase
            </v-chip>
            {
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >database
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >authentication
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >hosting
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >storage
            </v-chip>
            }
          </div>
        </v-col>
        <v-col
          cols="10"
          md="4"
          class="elevation-16 pa-4"
        >
          <h4 :class="`
            text-heading-5
            text-md-heading-4
            font-weight-bold
            ${themeColorText}
            ml-4
            text-decoration-underline
          `">Node.js frameworks</h4>
          <div class="text-body-2
            text-md-body-1
            mx-4"
          >
            <v-chip
              class="
                ma-2
                elevation-8
              "
              :color="skillsChipTitleColor"
            >
              <v-icon left>
              mdi-fire
              </v-icon>
              <span
              class="text-decoration-underline">
              Proficient:
              </span>
            </v-chip>
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >Axios
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >request
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >request-promise
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >bluebird
            </v-chip>
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >canvas
            </v-chip>
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >moment.js
            </v-chip>
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >ytdl-core
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >youtube-api
            </v-chip>
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >Discord.js
            </v-chip>
            <br />
            <v-chip
              class="
                ma-2
                elevation-8
              "
              :color="skillsChipTitleColor"
            >
              <v-icon left>
              mdi-pine-tree-fire
              </v-icon>
              <span
              class="text-decoration-underline">
              Familiar:
              </span>
            </v-chip>
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >node-schedule
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >chokidar
            </v-chip>
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >tmi.js
            </v-chip>
            +
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >twitch API
            </v-chip>
            <br />
            <br />
            <v-chip
              class="
                ma-2
                elevation-8
              "
              :color="skillsChipTitleColor"
            >
              <v-icon left>
              mdi-alert-decagram
              </v-icon>
              <span
              class="text-decoration-underline">
              Qualities:
              </span>
            </v-chip>
            <br />
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >Full-stack
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >OOP
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >Agile development
            </v-chip>
            <v-chip
              class="
                ma-1
                elevation-4
              "
              :color="skillsChipBodyColor"
            >REST API
            </v-chip>
          </div>
        </v-col>
      </v-row>
    </v-lazy>
  </v-container>
</template>

<script>
import { mapState, mapMutations } from 'vuex';

export default {
  computed: {
    ...mapState([
      'themeColorClass',
      'themeColorText',
      'skillsChipTitleColor',
      'skillsChipBodyColor',
      'skillsC',
      'skillsAc',
    ]),
  },
  methods: {
    ...mapMutations([
      'setSkillsC',
      'setSkillsAc',
    ]),
    onSkillsIntersect(entries) {
      this.setSkillsAc(entries[0].isIntersecting);
      this.setSkillsC(entries[0].isIntersecting);
    },
  },
};
</script>

<style>

</style>
